title: semver - Semantic versioning commandline client

# The description should be always in sync with the content
# of the mainpage of the homepage
description: >
  semver is a command processor for checking and manipulating 
  semantic version numbers on the commandline. It is primarily 
  intended for automation in continuous integration and continuous 
  delivery environments. It can also be used in scripts as well 
  as directly on the command line.
exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay
