<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.github.freiheitstools.semver.cli</groupId>
  <artifactId>semver</artifactId>
  <packaging>pom</packaging>
  <version>0.1.0-SNAPSHOT</version>
  <name>Semantic Versioning Commandline Client Parent</name>
  <url>https://github.com/freiheitstools/semver-cli</url>

  <licenses>
    <license>
      <name>Apache License version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>

  <scm>
    <connection>scm:git:git://github.com/freiheitstools/semver-cli.git</connection>
    <developerConnection>scm:git:ssh://github.com:freiheitstools/semver-cli.git</developerConnection>
    <url>https://github.com/freiheitstools/semver-cli</url>
  </scm>

  <properties>
    <os.family>will_be_changed_by_profiles_and_their_activation</os.family>
    <svc.picocli.version>4.7.7</svc.picocli.version>
    <svc.assertj-core.version>3.27.4</svc.assertj-core.version>
    <svc.junit.version>5.13.4</svc.junit.version>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <svc.java-language-level>22</svc.java-language-level>

    <!-- Controls the build of a native image of the tool -->
    <skipNativeBuild>false</skipNativeBuild>
    <svc.maven-minimal-version>3.9.0</svc.maven-minimal-version>
    <svc.semverparser.version>1.0.0</svc.semverparser.version>
    <svc.commons-lang3.version>3.18.0</svc.commons-lang3.version>
    <svc.maven-compiler-plugin.version>3.14.0</svc.maven-compiler-plugin.version>
    <svc.maven-enforcer-plugin.version>3.6.1</svc.maven-enforcer-plugin.version>
    <svc.maven-surefire-plugin.version>3.5.4</svc.maven-surefire-plugin.version>
    <svc.semverparser.version>1.0.0</svc.semverparser.version>
    <svc.commons-lang3.version>3.18.0</svc.commons-lang3.version>
    <svc.maven-jar-plugin.version>3.4.2</svc.maven-jar-plugin.version>
    <svc.native-image-maven-plugin.version>21.2.0</svc.native-image-maven-plugin.version>
    <svc.maven-assembly-plugin.version>3.7.1</svc.maven-assembly-plugin.version>
  </properties>

  <modules>
    <module>client</module>
  </modules>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.github.freiheitstools.semver.parser</groupId>
        <artifactId>parser</artifactId>
        <version>${svc.semverparser.version}</version>
      </dependency>
      <dependency>
        <groupId>info.picocli</groupId>
        <artifactId>picocli</artifactId>
        <version>${svc.picocli.version}</version>
      </dependency>
      <dependency>
        <groupId>org.assertj</groupId>
        <artifactId>assertj-core</artifactId>
        <version>${svc.assertj-core.version}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${svc.junit.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
        <version>${svc.commons-lang3.version}</version>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <profiles>
    <profile>
      <id>linux-build</id>
      <activation>
        <property>
          <name>os.name</name>
          <value>Linux</value>
        </property>
      </activation>
      <properties>
        <os.family>linux</os.family>
      </properties>
    </profile>
    <profile>
      <id>macos-build</id>
      <activation>
        <property>
          <name>os.name</name>
          <value>Mac OS X</value>
        </property>
      </activation>
      <properties>
        <os.family>mac</os.family>
      </properties>
    </profile>
    <profile>
      <id>windows-build</id>
      <activation>
        <property>
          <name>os.name</name>
          <value>Windows</value>
        </property>
      </activation>
      <properties>
        <os.family>windows</os.family>
      </properties>
    </profile>
  </profiles>

  <build>
    <defaultGoal>clean install</defaultGoal>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${svc.maven-surefire-plugin.version}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${svc.maven-jar-plugin.version}</version>
          <configuration>
            <skipIfEmpty>true</skipIfEmpty>
          </configuration>
        </plugin>

        <plugin>
          <groupId>org.graalvm.nativeimage</groupId>
          <artifactId>native-image-maven-plugin</artifactId>
          <version>${svc.native-image-maven-plugin.version}</version>
          <executions>
            <execution>
              <goals>
                <goal>native-image</goal>
              </goals>
              <phase>package</phase>
            </execution>
          </executions>
          <configuration>
            <imageName>semver-${project.version}-${os.family}.${os.arch}.bin</imageName>
            <mainClass>fhg.tooling.semver.cli.SemVer</mainClass>
            <buildArgs>--verbose</buildArgs>
            <skip>${skipNativeBuild}</skip>
          </configuration>
        </plugin>

        <plugin>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>${svc.maven-assembly-plugin.version}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${svc.maven-compiler-plugin.version}</version>
          <configuration>
            <encoding>UTF-8</encoding>
            <source>${svc.java-language-level}</source>
            <target>${svc.java-language-level}</target>
            <testSource>${svc.java-language-level}</testSource>
            <testTarget>${svc.java-language-level}</testTarget>
            <annotationProcessorPaths>
              <path>
                <groupId>info.picocli</groupId>
                <artifactId>picocli-codegen</artifactId>
                <version>${svc.picocli.version}</version>
              </path>
            </annotationProcessorPaths>
            <compilerArgs>
              <arg>-Aproject=${project.groupId}/${project.artifactId}</arg>
            </compilerArgs>
          </configuration>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <version>${svc.maven-enforcer-plugin.version}</version>
          <executions>
            <execution>
              <id>enforce-maven</id>
              <goals>
                <goal>enforce</goal>
              </goals>
              <configuration>
                <rules>
                  <requireMavenVersion>
                    <version>[${svc.maven-minimal-version},)</version>
                  </requireMavenVersion>
                  <requireJavaVersion>
                    <version>[${svc.java-language-level},)</version>
                  </requireJavaVersion>
                  <dependencyConvergence/>
                </rules>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
