name: XXX Build

on:
  workflow_dispatch:

jobs:
  XXX:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        jdk: [ 11, 14 ]
        distribution: [ zulu, adopt-hotspot, adopt-openj9 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ matrix.distribution }}

      - name: Setup local Maven Repository
        uses: actions/cache@v2
        env:
          cache-name: maven-local-repository-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}