name: Build and test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        jdk: [ 25 ]

    runs-on: ${{ matrix.os }}

    env:
      # The reference JDK and OS are needed to define which job of the matrix build is
      # allowed to upload the generated jar. Background: Uploading the same artifact multiple times
      # will cause all builds except the first one to fail
      REFERENCE_JDK_VERSION: '25'
      REFERENCE_OS_NAME: 'macos-latest'

    steps:
      - name: Checkout Git Repository
        id: git-checkout
        uses: actions/checkout@v6
        
      - uses: actions/setup-java@v5
        with:
          distribution: 'graalvm'
          java-version: '${{ matrix.jdk }}'

      - name: Show Versions of used tools
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          echo "Version of Java:" $(java --version)
          echo "Version of native-image:" $(native-image --version)
          echo "Version of Apache Maven:" $(mvn --version)

      - name: Determine build meta data
        id: determine_meta_data
        run: |
          PROJECT_VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
          echo "project_version=${PROJECT_VERSION}" >> ${GITHUB_OUTPUT}
          
          PROJECT_ARCH=$(mvn -q -DforceStdout help:evaluate -Dexpression=os.arch)
          echo "project_arch=${PROJECT_ARCH}" >> ${GITHUB_OUTPUT}
          
          PROJECT_FAMILY=$(mvn -q -DforceStdout help:evaluate -Dexpression=os.family)
          echo "project_family=${PROJECT_FAMILY}" >> ${GITHUB_OUTPUT}

      - name: Display extracted Maven build meta data
        run: |
          echo "Project version: " ${{ steps.determine_meta_data.outputs.project_version }}
          echo "Maven build architecture: " ${{ steps.determine_meta_data.outputs.project_arch }}
          echo "Maven OS family: " ${{ steps.determine_meta_data.outputs.project_family }}

      - name: Setup local cached Maven Repository
        id: setup-cached-repo
        uses: actions/cache@v5
        env:
          cache-name: maven-local-repository-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}

      - name: Build
        id: maven-build
        run: |
          mvn --no-transfer-progress --batch-mode clean install

      - name: Display Build Results
        id: show-result
        run: |
          ls -lha client/target/
            
          UEBERJAR_FILENAME=$( basename $( ls client/target/semver*.jar ))
          echo "ueberjar_filename=${UEBERJAR_FILENAME}" >> ${GITHUB_OUTPUT}

          NATIVE_FILENAME=$( basename $( ls client/target/semver*.bin ))
          NATIVE_FILENAME=$( basename $( ls client/target/semver*.bin ))
          echo "native_filename=${NATIVE_FILENAME}" >> ${GITHUB_OUTPUT}

      - name: Upload native binary
        uses: actions/upload-artifact@v5
        # The native binary can be only uploaded once for a plattform, therefore we have decided
        # to upload native binary only once for a given reference plattform
        if: matrix.jdk == env.REFERENCE_JDK_VERSION
        with:
          name: ${{ steps.show-result.outputs.native_filename }}
          path: client/target/${{ steps.show-result.outputs.native_filename }}
          if-no-files-found: error

      - name: Upload ueberjar
        uses: actions/upload-artifact@v5
        # The Ueberjar can be only uploaded once, therefore we have decided to upload
        # the artifact only once for a given reference plattform
        if: matrix.jdk == env.REFERENCE_JDK_VERSION && matrix.os == env.REFERENCE_OS_NAME
        with:
          name: ${{ steps.show-result.outputs.ueberjar_filename }}
          path: client/target/${{ steps.show-result.outputs.ueberjar_filename }}
          if-no-files-found: error
