name: XXX Build

on:
  workflow_dispatch:
  push:

jobs:
  XXX:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        # os: [ ubuntu-latest, macos-latest ]
        jdk: [ 11 ]
         #jdk: [ 11, 14, 15, 16 ]
        #distribution: [ zulu, adopt-hotspot, adopt-openj9 ]
        distribution: [ adopt-hotspot ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Git Repository
        id: git-checkout
        uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.jdk }}
        id: setup-jdk
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ matrix.distribution }}

      - name: Setup local cached Maven Repository
        id: setup-cached-repo
        uses: actions/cache@v2
        env:
          cache-name: maven-local-repository-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}

      - name: Building the Application with Maven
        id: maven-build
        timeout-minutes: 60
        shell: bash
        run: |
          set -e
          mvn -B -P -native \
              --no-transfer-progress \
              clean install
  YYYY:
    #needs: [ XXX ]
    strategy:
      fail-fast: false
      matrix:
        #os: [ macos-latest ]
        os: [ ubuntu-latest, macos-latest ]
        jdk: [ 11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Git Repository
        id: git-checkout
        uses: actions/checkout@v2

      - name: Setup local cached Maven repository
        id: setup-cached-repo
        uses: actions/cache@v2
        env:
          cache-name: maven-local-repository-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}

      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.2.0'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'

      - name: Install native-image component
        id: setup-graalvm-native-image
        shell: bash
        run: |
          set -x
          gu install native-image

      - name: Building the native application with Maven
        id: maven-build
        timeout-minutes: 60
        shell: bash
        run: |
          set -e
          mvn -B -P native \
              --no-transfer-progress \
              clean install

